#부모, 자식수
SELECT E.ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA AS E
    GROUP BY PARENT_ID
) P ON E.ID = P.PARENT_ID
ORDER BY E.ID ASC;