-- 코드를 입력하세요
-- 상품코드 별 매출액 합계를 출력

SELECT P.PRODUCT_CODE, P.PRICE * SUM(SALES_AMOUNT) SALES
FROM PRODUCT P
JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY S.PRODUCT_ID, P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;