-- 자동차 종류가 '세단' 또는 'SUV'인 자동차 중
-- 해당 기간에 대여 가능하고, 2022년 11월 1일 - 2022년 11월 30일
-- 30일간 대여 금액이 50만원 이상 200만원 미만인 자동차의 정보 출력
-- 자동차 정보 / 자동차 대여기록 정보 / 자동차종류별 대여기간 종류별 할인 정보 T

-- 대여 불가 자동차ID 목록 T
WITH CTE1 AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-12-01'
    AND END_DATE > '2022-10-31'
),

CTE2 AS (
    SELECT C.CAR_ID, C.CAR_TYPE, P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV') -- 차 종류
        AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CTE1) -- 대여 가능
        AND P.DURATION_TYPE = '30일 이상'
)

SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((C.DAILY_FEE * (1.00 - 0.01 * CTE2.DISCOUNT_RATE) * 30)) AS FEE
FROM CTE2
JOIN CAR_RENTAL_COMPANY_CAR C ON CTE2.CAR_ID = C.CAR_ID
WHERE FLOOR((C.DAILY_FEE * (1.00 - 0.01 * CTE2.DISCOUNT_RATE) * 30)) BETWEEN 500000 AND 1999999 -- 미만,,
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

