-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 정보 조회

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE -- 음식종류별 MAX 즐겨찾기 수
)
ORDER BY 1 DESC;