# 대장균 크기의 퍼센트 랭크 테이블
WITH COLONY_RANKING AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
    FROM ECOLI_DATA
)

SELECT ID,
CASE
WHEN SIZE_RANK * 100 <= 25 THEN 'CRITICAL'
WHEN SIZE_RANK * 100 <= 50 THEN 'HIGH'
WHEN SIZE_RANK * 100 <= 75 THEN 'MEDIUM'
ELSE 'LOW'
END COLONY_NAME
FROM COLONY_RANKING
ORDER BY ID;