-- 년,월,성별 별로 상품을 구매한 회원수를 집계

-- 년월별 구매자별 구매량 집계
WITH CTE AS (
    SELECT DISTINCT USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
) -- 회원별 년월별 구매 정보

SELECT YEAR, MONTH, GENDER, COUNT(*) USERS
FROM CTE C
JOIN USER_INFO U ON C.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY C.YEAR, C.MONTH, U.GENDER
ORDER BY 1,2,3;
