-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와
-- 상품을 구매한 회원의 비율을
-- 년, 월 별로 출력
-- (2021년에 가입한 회원 중 상품을 구매한 회원 수) / (2021년에 가입한 회원 수)
WITH JOINED_COUNT AS (
    SELECT COUNT(*) COUNT
    FROM USER_INFO U
    WHERE YEAR(JOINED) = '2021'
), -- 2021년 월별 가입한 회원 수


JOINED_SALES_COUNT AS (
    SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) COUNT
    FROM USER_INFO U
    JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
    WHERE YEAR(JOINED) = '2021'
    AND YEAR(SALES_DATE) = '2022'
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
)
-- 2021년 월별 가입한 회원 별 구매 수 중 구입한 회원의 수

-- SELECT * FROM JOINED_SALES_COUNT;


SELECT JS.YEAR, JS.MONTH, JS.COUNT PURCHASED_USERS, ROUND((JS.COUNT/J.COUNT),1) PURCHASED_RATIO
FROM JOINED_SALES_COUNT JS, JOINED_COUNT J
ORDER BY JS.MONTH;