# 자신의 세대 CTE
# 자식의 수
WITH RECURSIVE GENERATIONS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATIONS G ON E.PARENT_ID = G.ID
),

CHILD_COUNT AS (
    SELECT PARENT_ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) #각 부모의 자식수

#각 세대별 자식이 없는 대장균의 ID
SELECT COUNT(*) AS COUNT, GENERATION
FROM GENERATIONS G
LEFT JOIN CHILD_COUNT C ON G.ID = C.PARENT_ID
WHERE C.COUNT IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;