-- 코드를 작성해주세요
WITH CTE AS (
    SELECT ID,  CEIL(MONTH(DIFFERENTIATION_DATE)/3) QUARTER
    FROM ECOLI_DATA
)
SELECT CONCAT(QUARTER, 'Q') QUARTER, COUNT(*) ECOLI_COUNT
FROM CTE
GROUP BY QUARTER
ORDER BY QUARTER;