-- 생산일자가 2022년 5월인 식품들의 정보 조회
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1;