-- 자동차 종류가 트럭인 자동차의 대여 기록
-- 대여 기록 별로 대여 금액 (FEE) 를 구하여 대여 기록 ID, 대여 금액 릭스트를 출력
WITH TRUCK_DISCOUNT_PLAN AS (
    SELECT PLAN_ID, DISCOUNT_RATE,
            CASE 
            WHEN DURATION_TYPE LIKE '7%' THEN 1
            WHEN DURATION_TYPE LIKE '30%' THEN 2
            ELSE 3
            END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    UNION ALL
    SELECT 1 , 0, 0 -- 7일 미만 처리
), -- 기간별 트럭의 대여 할인 정책 T

CAR_RENT_DURATION AS (
    SELECT HISTORY_ID, CAR_ID, 
            CASE 
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN 3
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN 2
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN 1
            ELSE 0
            END DURATION_TYPE,
            DATEDIFF(END_DATE, START_DATE)+1 DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) -- 자동차 대여기간 컬럼 추가 T

SELECT D.HISTORY_ID, FLOOR(D.DURATION * C.DAILY_FEE * (1-P.DISCOUNT_RATE*0.01)) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENT_DURATION D ON C.CAR_ID = D.CAR_ID
JOIN TRUCK_DISCOUNT_PLAN P ON P.DURATION_TYPE = D.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
-- 자동차별 대여 금액