
-- 맛별 주문량
WITH CTE1 AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM CTE1
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;