-- 0시부터 23시까지, 각 시간대별로 입양이 몇건이나 발생했는지 조회
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS HOUR
    FROM CTE
    WHERE HOUR < 23
),
CTE2 AS (
    SELECT DISTINCT HOUR(DATETIME)
    FROM ANIMAL_OUTS
)

SELECT CTE.HOUR, CASE
             WHEN (CTE.HOUR NOT IN (SELECT * FROM CTE2))
             THEN 0
             ELSE COUNT(*)
             END COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS A
ON CTE.HOUR = HOUR(A.DATETIME)
GROUP BY CTE.HOUR;
