-- 코드를 작성해주세요
WITH FRONT_END_DEVELOPERS AS (
    SELECT DISTINCT D.ID
    FROM SKILLCODES S
    JOIN DEVELOPERS D ON D.SKILL_CODE & S.CODE = S.CODE
    WHERE S.CATEGORY = 'Front End'
)
    
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT ID FROM FRONT_END_DEVELOPERS
)
ORDER BY ID;