-- 리뷰를 가장 많이 작성한 회원의 리부 조회
-- 회원이름, 리뷰텍스트, 리뷰 작성일 출력
WITH MEMBER_REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID -- 회원별 리뷰 수
)

    
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN 
    (SELECT MEMBER_ID
     FROM MEMBER_REVIEW_COUNT 
     WHERE COUNT = (SELECT MAX(COUNT) FROM MEMBER_REVIEW_COUNT))
ORDER BY REVIEW_DATE, REVIEW_TEXT;