#아이템의 희귀도가 rare인 아이템들의 모든 다음 업그레이드 아이템의 아이템ID, 아이템명, 희귀도를 출력
#정렬 - 아이템id 기준 내림차순
SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS II
JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (
 SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;