#부모의 형질을 모두 보유한 대장균의 ID
#부모 형질 테이블
SELECT ID, GENOTYPE, PARENT_GENOTYPE
FROM ECOLI_DATA AS E
JOIN (
    SELECT ID AS PARENT_ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) AS G ON E.PARENT_ID = G.PARENT_ID
WHERE E.GENOTYPE & G.PARENT_GENOTYPE = G.PARENT_GENOTYPE
ORDER BY ID;