-- 대여시작일 기준 기간 내 대여횟수 5회 이상인 자동차
-- 해당 기간 내 월별, 자동차별 대여 횟수
WITH CTE AS (
    SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
) -- 기간 내 자동차별 대여횟수 CTE

SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID FROM CTE WHERE RECORDS >= 5
)
AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY 1, 2 DESC;

