-- 코드를 작성해주세요
# WITH MAX_DIFF AS(
#     SELECT YEAR(DIFFERENTIATION_DATE) as year, MAX(SIZE_OF_COLONY) AS MAX_DF
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)
# )
# SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (select md.MAX_DF from max_diff md where md.year = ed.YEAR(ED.DIFFERENTIATION_DATE))-SIZE_OF_COLONY AS YEAR_DEV, ED.ID
# FROM ECOLI_DATA ED
# ORDER BY YEAR, YEAR_DEV

# 연도, 해당 연도에서 가장 큰 크기
WITH BIGGEST AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT MAX_SIZE
        FROM BIGGEST B
        WHERE B.YEAR = YEAR(E.DIFFERENTIATION_DATE)
    ) - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
    FROM ECOLI_DATA E
    ORDER BY YEAR, YEAR_DEV;