# BOOK 테이블에서 2021년 출판된 '인문' 카테고리에 속하는 도서 리스트를 찾아
# 도서ID, 출판일을 출력
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE, '%Y') = '2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;