WITH CTE AS (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
) -- 사원별 2022년 평가점수

SELECT SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES H
JOIN CTE C ON H.EMP_NO = C.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE) FROM CTE)
ORDER BY H.EMP_NO;