# SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD b
# JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
# WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;



# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
# WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B 
JOIN USED_GOODS_REPLY AS R ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;














