-- 식품분류별로 가격이 제일 비싼 식품의 정보 조회
WITH TOP_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, PRICE
    FROM TOP_PRICE
)
ORDER BY PRICE DESC;
