-- 평균 길이가 33 이상인 물고기들을 종류별로 분류하여 잡은 수, 최대 길이, 종류 출력

WITH FI AS (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) LENGTH
    FROM FISH_INFO
) -- 길이 보정

SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM FI
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;
