-- 코드를 작성해주세요

WITH CTE AS (
    SELECT ID, EMAIL, S.CODE, S.CATEGORY, S.NAME
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
), -- 개발자별 언어 테이블

-- 개발자, 그룹으로 
CTE2 AS (SELECT
    CASE
    WHEN ((ID, 'Python') IN (SELECT ID, NAME FROM CTE) 
          AND (ID, 'Front End') IN (SELECT ID, CATEGORY FROM CTE)) THEN 'A'
    WHEN ((ID, 'C#') IN (SELECT ID, NAME FROM CTE)) THEN 'B'
    WHEN ((ID, 'Front End') IN (SELECT ID, CATEGORY FROM CTE)) THEN 'C'
    END GRADE, 
         ID, EMAIL
    FROM DEVELOPERS
)

SELECT *
FROM CTE2
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;